### ISSUE TITLE
CAL (netinstall) roadmap

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#78]
Continue discussion from #77 

ToDo in CAL:
- [x] decide how we organize netinstall.yaml groups
- [x] rework modules and add new modules
- [x] entirely support openrc

ToDo in manjaro-tools:
- [x] drop iso configuration code, move it to either livecd repo or CAL

**Comment by udeved** [comment]
Status update:

We now have:

* classic offline iso option
* hybrid option that installs additional packages
* online bootstrap, everything is downloaded, un image is unpacked

In my view, the hybrid option is attractive to drop the full profiles, and use the minimal profiles as base install and pull the many extra stuff from online, eg libreoffice, java, steam

What we need to work out:

* how to come up with a manageable yaml solution in terms of file(idea, make package lists yaml based)
* how to integrate openrc without the need of separate files(partially a calamares module thing to address eventually)
* find ideal hybrid groups taht the profiles share(gtk and qt groups?)

**Comment by philmmanjaro** [comment]
How far are we with this. Do we include **netinstall** with Manjaro 16.10 or do we skip it and release it with Manjaro 17.x?

**Comment by udeved** [comment]
It really depends on some decisions in my view.

Do we want to keep mhwd repo on iso?
Technically, we could drop it, which makes install media internet depend for drivers, and start iso with preinstalled free drivers. selection screen in syslinux would only set CAL for free/nonfree?

Further, my idea was to take the 4 minimal profiles we support currently in netinstall, and add for a full install package groups, which would also make CAL internet depend. This would drastically simplify everything. We would end up with minimal profiles unsquashed, and extra software instaled from internet?

**Comment by philmmanjaro** [comment]
Well, we have the **classic mode**, which needs the **mhwd repo** and the **netinstaller** mode, which can be redesigned completely. However we should not remove the **classic mode** during this process. If syslinux gets edited, it should be logical to the given modes. Simplification I see in netinstall already. However the visuals need to be improved, at least in CAL.

**Comment by udeved** [comment]
We have a 3rd mode, unsquash and install packages. We could even install them from repo on iso. But that would be step backwards I think.
I think this would be ideal to pull in java, office, media apps in the minimal profiles.
We could drop the full profiles and add the additional software with CAL?

**Comment by udeved** [comment]
CAL
|
|--- unpack
|--- netinstall
      |--- chrootcfg (replaces unpackfs)
      |--- packages (uses unpackfs)

**Comment by philmmanjaro** [comment]
If you have a classic install media it might be outdated. So we have to unsquash > update the target system > then install software.

**Comment by udeved** [comment]
Shouldn't be a problem, afaik, packages module calls pacman -Sy <list>. we could add option to update.

**Comment by philmmanjaro** [comment]
Well, most of this I see with Manjaro 17.x ...

**Comment by udeved** [comment]
I don't care much about that, we can throw out test build until final integration.
If you said, "do what you have to do to simplify profiles and stuff" I would remove the mhwd repo layer, since I think it does not matter if you need internet at install or afterwards, and having an current install is preferable over updating afterwards..

**Comment by udeved** [comment]
Btw, a really cool feature would be to have a driver(fee/nonfree) selection widget on a possible mhwdcfg page, but afaik, we would have to port it to c++.
Or is there a way to add eg pyqt pages?

**Comment by udeved** [comment]
https://github.com/calamares/calamares/tree/pythonqt

Looks like excellent addition, regarding eg free/nonfree, or branch selection widgets.
